name: # the name of the action
description: # additional descriptive info about the action
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  remote_name:
    description: 'The name of the remote repository (default: origin)'
    required: false
    default: 'origin'
  github_token:
    description: Github authorisation token
    required: true
  ignore_branches:
    description: List of branch patterns to ignore when cleaning up trailing branches
    required: false
    default: 'hotfix/* feature/*'
outputs:
  cleaned:
    description: list of cleaned up branched (space separated)


# for additional options, see: https://help.github.com/en/articles/metadata-syntax-for-github-actions
